name: Pull Request Workflow Cancel Example
on: [pull_request]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Running now'
      - run: sleep 10
      - run: sleep 10
      - run: sleep 10
      - uses: tutu-ru-mobile/cancel-previous-pull-request@master
        with:
          access_token: "${{ secrets.GITHUB_TOKEN }}"
      - run: sleep 10
      - run: sleep 10
      - run: sleep 10
      - run: echo 'wasnt cancelled'
